
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Default Application</title>
  <link rel="stylesheet" type="text/css" href="../js/extjs/theme-crisp/resources/theme-crisp-all-debug.css">
  <script type="text/javascript" src="../js/extjs/ext-all-debug.js"></script>
  <link rel="stylesheet" type="text/css" href="../css/style.css">
 
</head>
<body>
	<div id="header">
		
				<div class="main-nav">
					<div class="logo">
						<img src="../css/pictures/alegra.png">
					</div>


					<div class="menu">
						<ul>
							<li><a href="https://ayuda.alegra.com/hc/es">Ayuda</a></li>
							<li><a href="" class="dropdown">Soporte</a></li>
							<li><a href="https://app.alegra.com/user/view/id/1">Correo</a></li>
							<li><a href="https://app.alegra.com/configuration">Configuracion</a></li>
							<li><a href="" >Salir</a></li>
						</ul>
					</div>
				</div>

				<div class="barrita">
					
					<div class="menubarrita">
							<ul>
								<li><a href="https://app.alegra.com" >Inicio</a></li>
								<li><a href="https://app.alegra.com/invoice" >Ingresos</a></li>
								<li><a href="https://app.alegra.com/payment" >Gastos</a></li>
								<li><a href="https://app.alegra.com/client" >Contactos</a></li>
								<li><a href="https://app.alegra.com/item" >Inventarios</a></li>
								<li><a href="https://app.alegra.com/account" >Bancos</a></li>
								<li><a href="https://app.alegra.com/category" >Categorias</a></li>
								<li><a href="https://app.alegra.com/report" >Reportes</a></li>
							</ul>
					</div>
					
	
				</div>	


	</div>


	

	
	<?php echo $this->layout()->content; ?>
	<hr />
</body>




<div class		=	"general">

	<div class="helpcontact" >
		<h3>Ayudas paso a paso</h3>
		<p><a href="http://ayuda.alegra.com/hc/es/articles/205798409-Cómo-hacer-una-Factura-de-venta-">Cómo crear una factura de venta</a></p>	
		<p><a href="http://ayuda.alegra.com/hc/es/articles/206509365--Cómo-crear-una-Factura-de-Proveedor-">Cómo crear una factura de proveedor</a></p>	
		<p><a href="http://ayuda.alegra.com/hc/es/articles/206509615--Cómo-importar-contactos-">Cómo importar contactos</a></p>	
		<p><a href="https://ayuda.alegra.com/hc/es/articles/206512955--Cómo-crear-un-Banco-">Cómo crear una cuenta de Banco</a></p>	
		<p><a href="https://ayuda.alegra.com/hc/es/articles/206509105-Agregar-un-pago-a-una-factura">Cómo registrar un pago a una factura de venta</a></p>	
		<p><a href="https://ayuda.alegra.com/hc/es/articles/205798349--Cómo-crear-una-Nota-Crédito-">Cómo crear una nota crédito</a></p>	


	</div>
	
	<div class="support">
		<h3>Soporte</h3>
		<p><a href="">Contactos</a></p>	
		<p><a href="https://ayuda.alegra.com/hc/es">Centro de ayuda</a></p>	
		<p><a href="https://www.alegra.com/colombia/manual.pdf">Manual de primeros pasos en Alegra</a></p>	
		<p><a href="https://www.alegra.com/acrecer-con-alegra">Plan de referidos</a></p>	
		<p><a href="https://ayuda.alegra.com/hc/es/articles/205761789-Caso-de-éxito"W>Comparte tu historia</a></p>	

	</div>

	<div class="contact">
		<h3>Contactos</h3>
		<p><a href="https://ayuda.alegra.com/hc/es/articles/206509595--Cómo-crear-un-cliente-y-o-proveedor-">¿Como crear un cliente?</a></p>	
		<p><a href="https://ayuda.alegra.com/hc/es/articles/206509615--Cómo-importar-contactos-">¿Como importar contactos?</a></p>	

	</div>

</html>
<script type="text/javascript">
	(function() {
		Ext = window.Ext || {};
	});
</script>

